"""Add course_load_id to Task

Revision ID: 31f009b37812
Revises: d67c8216804d
Create Date: 2025-04-30 09:12:32.272596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31f009b37812'
down_revision = 'd67c8216804d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_load_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'course_loads', ['course_load_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('course_load_id')

    # ### end Alembic commands ###
