"""update task

Revision ID: 36449c7f3c2d
Revises: cca0a5d58170
Create Date: 2025-06-13 23:53:28.784640

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '36449c7f3c2d'
down_revision = 'cca0a5d58170'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_loads')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_loads',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('subject_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('weekly_hours', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('priority', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('next_exam', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name='course_loads_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='course_loads_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
