"""Initial migration

Revision ID: 41364f34bf16
Revises: 
Create Date: 2025-04-11 10:36:16.528143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41364f34bf16'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('university', sa.String(length=100), nullable=False),
    sa.Column('academic_program', sa.String(length=100), nullable=False),
    sa.Column('current_semester', sa.Integer(), nullable=False),
    sa.Column('enrollment_number', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
