"""create users table

Revision ID: 56b9f3d0e05e
Revises: 
Create Date: 2025-04-29 19:19:26.165053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56b9f3d0e05e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planning_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('max_daily_hours', sa.Integer(), nullable=False),
    sa.Column('preferred_days', sa.String(length=120), nullable=True),
    sa.Column('rest_days', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planning_preferences')
    # ### end Alembic commands ###
