"""deepseek implementation

Revision ID: 815928755198
Revises: a3862da7ffde
Create Date: 2025-06-13 20:09:36.870963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '815928755198'
down_revision = 'a3862da7ffde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('schedule_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_schedules')
    # ### end Alembic commands ###
